services:
  postgres:
    image: postgres:16-alpine
    container_name: events-postgres
    environment:
      POSTGRES_USER: eventsuser
      POSTGRES_PASSWORD: eventspass
      POSTGRES_DB: eventsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: